name: CI and CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Quasar Build
      run: |
        yarn global add @quasar/cli
        yarn install
        npx quasar build

