name: CI and CD

on:
  push:
    branches:
      - master
      - ci-cd
  pull_request:

jobs:
  build-quasar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup NodeJS
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Quasar Build
        run: |
          yarn global add @quasar/cli
          yarn install
          npx quasar build
      - uses: actions/upload-artifact@master
        with:
          name: dist-folder
          path: dist/spa

  build-image:
    runs-on: ubuntu-latest
    needs: build-quasar
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@master
        with:
          name: dist-folder
          path: dist
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: irripi2/irrifront
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: Dockerfile.prod

